### ISSUE TITLE
Using a licensed version of Dock Manager

### ISSUE THREAD

**Issue by tsalais** [brianlagunas/BlazorDockManagerWC#2]
You show us how to connect to NPM to load the trial version of Dock Manager with the following code:
import { defineCustomElements } from 'https://unpkg.com/igniteui-dockmanager@1.0.3/loader/index.mjs

I purchased Professional 20.2 and would like to use the licensed version.  Can you show me (or us as in everybody) how to access our licensed version of Dock Manager or any control in Ignite UI.  Actually, I'd like to use the Infragistics CDN instead of NPM.  Whatever it's turned into, it's still Node.JS. I don't even have it loaded on my machine, so I can't execute commands like npm install.  My email address is tsalais@outlook.com.  I am a registered user of Infragistic products.

**Comment by brianlagunas** [comment]
You'll need to connect to the IG npm feed.  You can read about how to do that here:

https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing

I may do a youtube video on how to do this. Thanks for the idea.

We currently don't have a CDN for our web components.

if you have any problems let me know.

**Comment by tsalais** [comment]
It’s very unclear what I’m supposed to do here.  First of all, the link you sent is primarily on angular.  I do see the mention that the Dock Manager Web Component is a separate package, but it doesn’t specify how to reference that package.  There is a link to the licensed Infragistics feed:

https://packages.infragistics.com/npm/js-licensed/?_ga=2.145868658.798757582.1612216052-1560470278.1607381312&_gac=1.86032746.1611582937.CjwKCAiA9bmABhBbEiwASb35V8jgYg1bI_LgFh2xNsMqR8lAB2HyyPBgwZqwlhXXF-0wmZWxUQl41BoCr-wQAvD_BwE

But do I just reference igniteui-dockmanager after this or what????  The trial version reference in your Blazor DockManager demo includes /loader/index.mjs and it also includes a reference to unpkg.com.

In the documentation for the Dock Manager, it specifies to execute the following command:
Npm install –save igniteui-dockmanager

I don’t even have Node.js (or Npm) installed on my computer.

I just need the exact Url to replace into the following code:
import { defineCustomElements } from 'https://unpkg.com/igniteui-dockmanager@1.0.3/loader/index.mjs';

I just purchased the latest version (20.2), but I really didn’t expect it to be this difficult.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brianlagunas** [comment]
The license feed is the same for Angular as it is Web components (which is what the Dock Manager is). Here is the web component doc topic:

https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/general-licensing.html

For the licensed product, you must use NPM. There is no simple link to use. It is only shipped via NPM packages.

I have a video no how to use NPM in Blazor. You can view it here:

https://youtu.be/hZPMNzokXHM

This should help you install the licensed dock manager using NPM into your Blazor project.

There was some changes tot he webpack script syntax since I recorded this, so if you have any issues let me know.
